// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXuSGAYxr9N4jLjXdnuT-j_jLS8QrcWoo',
    appId: '1:98638331512:web:eeaea1d3976d8fdc6ff78d',
    messagingSenderId: '98638331512',
    projectId: 'flutter-instagram-4e143',
    authDomain: 'flutter-instagram-4e143.firebaseapp.com',
    storageBucket: 'flutter-instagram-4e143.appspot.com',
    measurementId: 'G-1GFVR9WHX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhpLJAagDFZWHIbdQXnbWEbXEB9-NxWHQ',
    appId: '1:98638331512:android:fc7ba70e50312f1f6ff78d',
    messagingSenderId: '98638331512',
    projectId: 'flutter-instagram-4e143',
    storageBucket: 'flutter-instagram-4e143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-309DCJsFKDTd_DQos6kKne9xB6F73jc',
    appId: '1:98638331512:ios:d32c862c4d72348a6ff78d',
    messagingSenderId: '98638331512',
    projectId: 'flutter-instagram-4e143',
    storageBucket: 'flutter-instagram-4e143.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-309DCJsFKDTd_DQos6kKne9xB6F73jc',
    appId: '1:98638331512:ios:2fba9e8a80cf0bed6ff78d',
    messagingSenderId: '98638331512',
    projectId: 'flutter-instagram-4e143',
    storageBucket: 'flutter-instagram-4e143.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
